/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui {
    export class gameSceneUI extends Scene {
		public lblCountDwonValue:Laya.Label;
		public lblScoreValue:Laya.Label;
		public containerMouse:Laya.Sprite;
		public dialogGameOver:Laya.Sprite;
		public lblScoreCurrentValue:Laya.Label;
		public lblScoreHighestValue:Laya.Label;
		public btnPlayAgain:Laya.Image;
		public lblBtnTitle:Laya.Label;
		public hammer:Laya.Image;
		public containerScoreFloat:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("gameScene");
        }
    }
    REG("ui.gameSceneUI",gameSceneUI);
    export class startViewUI extends Scene {
		public startGame:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("startView");
        }
    }
    REG("ui.startViewUI",startViewUI);
}